### ISSUE TITLE
It's says this program is halal and then crashes

### ISSUE THREAD

**Issue by ahmadjerjawi** [BloodyToolzz/Bloody-Proxy-Scraper-V2#1]
██████╗ ██╗      ██████╗  ██████╗ ██████╗ ██╗   ██╗
              ██╔══██╗██║     ██╔═══██╗██╔═══██╗██╔══██╗╚██╗ ██╔╝
              ██████╔╝██║     ██║   ██║██║   ██║██║  ██║ ╚████╔╝
              ██╔══██╗██║     ██║   ██║██║   ██║██║  ██║  ╚██╔╝
              ██████╔╝███████╗╚██████╔╝╚██████╔╝██████╔╝   ██║
              ╚═════╝ ╚══════╝ ╚═════╝  ╚═════╝ ╚═════╝    ╚═╝

              ██████╗ ██████╗  ██████╗ ██╗  ██╗██╗   ██╗
              ██╔══██╗██╔══██╗██╔═══██╗╚██╗██╔╝╚██╗ ██╔╝
              ██████╔╝██████╔╝██║   ██║ ╚███╔╝  ╚████╔╝
              ██╔═══╝ ██╔══██╗██║   ██║ ██╔██╗   ╚██╔╝
              ██║     ██║  ██║╚██████╔╝██╔╝ ██╗   ██║
              ╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝

              ███████╗ ██████╗██████╗  █████╗ ██████╗ ███████╗██████╗
              ██╔════╝██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
              ███████╗██║     ██████╔╝███████║██████╔╝█████╗  ██████╔╝
              ╚════██║██║     ██╔══██╗██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
              ███████║╚██████╗██║  ██║██║  ██║██║     ███████╗██║  ██║
              ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝
              A simple proxy scraper made by Bloody.
              github/BloodyToolzz
This program is: Halal
Started at: 2022/10/13 23:31:05

**Comment by BloodyToolzz** [comment]
It randomly says halal or haram, I added it for fun. Did you run setup.bat to install the required modules?
